# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Louis addon
version: "1.2.0"
slug: louis-addon
description: Example add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - backup:rw
  - share:rw
  - media:rw
options:
  message: ""
  secret_key: ""
  api_key: ""
  ota_key: ""
schema:
  message: "str?"
  secret_key: "str?"
  api_key: "str?"
  ota_key: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
panel_icon: "mdi:home-assistant"
panel_title: "Louis Addon"