{
  "name": "ESPHome Log Viewer",
  "version": "1.0.0",
  "slug": "esphome_log_viewer",
  "description": "A Home Assistant add-on to connect to ESPHome devices via Native API and display logs.",
  "url": "https://github.com/LOUISCHTLAB/louis-addon.git",
  "arch": ["armhf", "armv7", "aarch64", "amd64", "i386"],
  "init": false,
  "map": ["config:rw", "ssl:rw", "share:rw"],
  "options": {
    "device_ip": "",
    "password": "",
    "encryption_key": "",
    "port": 6053
  },
  "schema": {
    "device_ip": "str",
    "password": "str",
    "encryption_key": "str",
    "port": "port"
  },
  "image": "ghcr.io/home-assistant/{arch}-addon-example"
}